# EconomyPlus made by _ItsWagPvP
# https://github.com/ItsWagPvP/EconomyPlus

# Don't modify this as it's to verify your config version
version: ${project.version}

# Send stacktraces when there are errors?
debug: false

# Translators' credits for their valuable contributions
# Supported languages: EN, IT, RO, AL, DE, ZH, FR, RU, ES
language: EN

# Enable bStats to collect plugin usage statistics?
# https://bstats.org/plugin/bukkit/EconomyPlus/11565
bStats: true

# Plugin integration hooks
hooks:
  PlaceholderAPI: true
  HolographicDisplays: true

# Plugin updater settings
updater:
  enabled: true
  # Get update notifications (requires permission: economyplus.update)
  notify-on-update: true
  # Automatically update the configuration file
  auto-update-config: true

# Sound settings
sounds:
  enabled: true
  success: ENTITY_PLAYER_LEVELUP  # Sound played on successful actions
  failed: ENTITY_VILLAGER_NO  # Sound played on failed actions

# Permission settings for basic commands
require-basic-command-permissions: true

# Currency formatting options
formatting:
  use-integers-only: false # Use integers for currency values instead of decimals\
  decimals:
    # Use decimal values for currency?
    enabled: true
    # Remove extra zeros for integers? (e.g., 12.00 becomes 12)
    excessive-zeros: false
    # Round up decimals? (e.g., 10.005 becomes 10.01)
    round-up: false
  letters: # Currency abbreviations for placeholders
    1000: k
    1000000: M
    1000000000: B
    1000000000000: T
    1000000000000000: Q
  custom-pattern:
    # Enable custom formatting pattern for %money% placeholder (excluding %money_formatted%)
    enabled: true
    value: '###,###.##'

# Initial starting balance for new players
starting-amount:
  balance: 0
  bank: 0

# Economy reset options
reset-economy:
  flags: true # Enable the use of @a or * when resetting balances
  console-only: true # Restrict the reset command to console only

# Player balance modification settings
balance-modification:
  offline-players: true # Allow modification of balances for offline players
  never-played: false # Allow modification of balances for players who haven't played before

# Balance top settings
balance-top:
  command:
    format: '&6%number%) &f%player%: &c$%money%'
    # Header displayed in /baltop command
    header:
      - '&8&m-----------------'
      - '&d&lBalance Top (Page %page%)'
      - '&8&m-----------------'
    # Enable or disable the footer
    use-footer: true
    footer:
      - ''
  hologram:
    # Refresh rate of holograms (in seconds)
    refresh-rate: 60
    format: "&6%number%) &f%player%: &c$%money%"
    header:
      - '&8&m-----------------'
      - '&d&lBalance Top'
      - '&8&m-----------------'
    # Enable or disable the footer
    use-footer: true
    footer:
      - ''

database:
  cache:
    # How frequently to refresh the cache (seconds)
    auto-save: 300
  # Can be either UUID or USERNAME
  mode: UUID
  # Choose database type (H2, MySQL, YAML)
  type: H2
  MySQL:
    # Database host
    host: localhost
    # Database port
    port: 3306
    # MySQL username
    username: root
    # MySQL password
    password: qwerty
    # Database name
    database: EconomyPlus
    # Database table name
    table: economy
    # Auto-reconnect to the database if connection is lost
    auto-reconnect: true
    # Use SSL certificate for database connection
    useSSL: false

# Bank settings
bank:
  enabled: true  # Use the bank feature?
  interest:
    # Enable interest feature
    enabled: true
    # Frequency of interest addition (in seconds)
    frequency: 300
    # Interest rate as a percentage
    percentage: 10
    # Require player to be online to receive interest?
    require-player-online: true