# EconomyPlus made by _ItsWagPvP
# https://github.com/ItsWagPvP/EconomyPlus

# Don't modify this as it's to verify your config version
version: ${project.version}

# Send stacktrace errors?
debug: false

# Translators' credits for their valuable contributions
# Supported languages: EN, IT, RO, AL, DE, ZH, FR, RU, ES
language: EN

# Enable bStats to collect plugin usage statistics?
# https://bstats.org/plugin/bukkit/EconomyPlus/11565
bStats: true

# Plugin integration hooks
hooks:
  PlaceholderAPI: true
  HolographicDisplays: true

# Plugin updater
updater:
  enabled: true
  notify-on-update: true # Get notifications (requires permission: economyplus.update)
  auto-update-config: true # Automatically update the configuration file

# Sound options
sounds:
  success:
    use: true
    sound: ENTITY_PLAYER_LEVELUP
  failed:
    use: true
    sound: ENTITY_VILLAGER_NO

# Permission for basic commands
require-basic-command-permissions: true

# Formatting options
formatting:
  use-integers-only: false # Use integers for currency values instead of decimals?
  # Formatting decimals
  decimals:
    enabled: true # Use decimal values for currency?
    excessive-zeros: false # Have zeros for integers? (e.g., 12 becomes 12.00).
    round-up: false # Round up decimals? (e.g., 10.005 would be 10.01)
  # Currency abbreviations for the formatted placeholders
  letters:
    1000: k
    1000000: M
    1000000000: B
    1000000000000: T
    1000000000000000: Q
  # Custom pattern for money placeholders (excludes formatted)
  custom-pattern:
    enabled: true
    value: '###,###.##'

# Starting balance for new players
starting-amount:
  balance: 0
  bank: 0

# Economy reset options
reset-economy:
  flags: true # Enable the use of @a or * when resetting balances?
  console-only: true # Restrict the reset command to console only?

# Balance modification options
balance-modification:
  offline-players: true # Enable modifying balances of offline players?
  never-played: false # Enable modifying balances of never played players?

# Balance top settings
balance-top:
  command:
    format: '&6%number%) &f%player%: &c$%money%'
    header: # Header displayed when executing /balancetop
      - '&8&m-----------------'
      - '&d&lBalance Top (Page %page%)'
      - '&8&m-----------------'
    # Footer settings
    use-footer: false
    footer:
      - ''
  hologram:
    refresh-rate: 60 # Refresh rate of holograms (in seconds)
    format: "&6%number%) &f%player%: &c$%money%"
    header: # Header displayed on the hologram
      - '&8&m-----------------'
      - '&d&lBalance Top'
      - '&8&m-----------------'
    # Footer settings
    use-footer: false
    footer:
      - ''

# Cache options
cache:
  auto-save: 300 # How frequently the cache refreshes (seconds)

# Database options
database:
  # Storage options
  storage:
    mode: UUID # Can be either UUID or USERNAME
    type: H2 # Choose database type (H2, MySQL, YAML)
  # MySQL settings
  MySQL:
    # Database host
    host: localhost
    # Database port
    port: 3306
    # MySQL username
    username: root
    # MySQL password
    password: qwerty
    # Database name
    database-name: EconomyPlus
    # Database table name
    table-name: economy
    # Attempt to reconnect to the database if connection is lost?
    auto-reconnect: true
    # Use SSL certificate for database connection?
    useSSL: false

# Bank options
bank:
  enabled: true  # Enable the bank feature?
  interest:
    # Enable interest feature
    enabled: true
    # Frequency of interest addition (in seconds)
    frequency: 300
    # Interest rate as a percentage
    percentage: 10
    # Require player to be online to receive interest?
    require-player-online: true