#  ╔════════════════════════════════════════════════════════════════════════════════════════════════╗
#  ║ ███████╗░█████╗░░█████╗░███╗░░██╗░█████╗░███╗░░░███╗██╗░░░██╗██████╗░██╗░░░░░██╗░░░██╗░██████╗ ║
#  ║ ██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗████╗░████║╚██╗░██╔╝██╔══██╗██║░░░░░██║░░░██║██╔════╝ ║
#  ║ █████╗░░██║░░╚═╝██║░░██║██╔██╗██║██║░░██║██╔████╔██║░╚████╔╝░██████╔╝██║░░░░░██║░░░██║╚█████╗░ ║
#  ║ ██╔══╝░░██║░░██╗██║░░██║██║╚████║██║░░██║██║╚██╔╝██║░░╚██╔╝░░██╔═══╝░██║░░░░░██║░░░██║░╚═══██╗ ║
#  ║ ███████╗╚█████╔╝╚█████╔╝██║░╚███║╚█████╔╝██║░╚═╝░██║░░░██║░░░██║░░░░░███████╗╚██████╔╝██████╔╝ ║
#  ║ ╚══════╝░╚════╝░░╚════╝░╚═╝░░╚══╝░╚════╝░╚═╝░░░░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚══════╝░╚═════╝░╚═════╝░ ║
#  ╚════════════════════════════════════════════════════════════════════════════════════════════════╝

# WARNING NOTE: look into playerhandler remove save username

# EconomyPlus made by _ItsWagPvP
# Watch the full resource on https://github.com/ItsWagPvP/EconomyPlus

# Do not change this!
# This is used to verify your config version
version: ${project.version}

# Credit to all translators for contributing.
# EN, IT, RO, AL, DE, ZH, FR, RU, ES
language: EN

# bStats system (https://bstats.org/plugin/bukkit/EconomyPlus/11565)
metrics: true

# Will send plugin's internal logs to console
debug: false

# Integrates with other plugins to enhance functionality.
hooks:
  PlaceholderAPI: true # Placeholders
  HolographicDisplays: true

# You want to enable the updater?
updater:
  use: true # Enable the plugin's auto update feature?
  notifications: true # Receive notifications when you join (if you have the perm "economyplus.update")
  config-updater: true # Enables the config to be updated automatically.
  check-github: 1 # Amount of days before the server will check for release on GitHub. 0 will check github every start up

# Plays success/error sounds to player after an action.
sounds:
  use: true
  error: ENTITY_VILLAGER_NO
  success: ENTITY_PLAYER_LEVELUP

# Require permissions for commands that aren't administrative?
require-basic-permissions: true

formatting:
  use-decimals: true
  have-excessive-zeros: false # 12 = 12.00
  round-decimals: false # 10.005 = 10.01

formatted-placeholder: # Used to format the %economyplus_money_formatted% & %money_formatted% placeholder
  1000: k
  1000000: M
  1000000000: B
  1000000000000: T
  1000000000000000: Q

# This will only work with %money% and not with %money_formatted%
pattern:
  use: true
  value: '###,###.##'

# Set a user balance on join
starting-balance: 0

# Set a user bank on join
starting-bank-balance: 0

# Reset All
reset-all:
  flags: true # Allows you to use @a or * when resetting balances.
  console-only: true # Command only works in console

purge-invalid: false # Remove invalid users automatically?

# Able to set people who have never played before balances
set-invalid: false # Save-Usernames must be enabled if your using this! It will prevent "Invalid User" and purging of invalid accounts!
save-usernames: true # Save usernames? (Attempts to prevent "Invalid User" issues)

# Baltop configuration
balance-top:
  chat:
    # Like 1) _ItsWagPvP: $100
    player-format: '&6%number%) &f%player%: &c$%money%'
    # The header of /baltop
    header:
      - '&8&m-----------------'
      - '&d&lBalTop (Page %page%)'
      - '&8&m-----------------'
  # This is for the hologram! (/ep hologram)
  hologram:
    # Refresh rate of holograms!
    refresh-rate: 60 # <- In seconds
    player-format: '&6%number%) &f%player%: &c$%money%'
    header:
      - '&8&m-----------------'
      - '&d&lBalTop'
      - '&8&m-----------------'

# Select how to storage the data
database:
  # Cache settings for better db performances
  Cache:
    # How much frequently the plugin should refresh the cache?
    # Does not affect player moneys or placeholders
    # It's only for security purposes
    # Default: 300 = 5 Minutes
    auto-save: 300 # <- In seconds
    # How many frequently the cache needs to be
    # refreshed with the MySQL db?
    MySQL: 10 # <- In seconds
  # You can choose one from UUID or NICKNAME
  mode: UUID
  # H2 (database.db)
  # MySQL
  # YAML (data.yml)
  type: H2
  # If you have set Type to H2 or YAML you have to ignore this options
  # Localhost connection
  host: localhost
  # Default is 3306
  port: 3306
  # The user for use MySQL connection
  username: root
  # Password of the user
  password: qwerty
  # Database name
  database: EconomyPlus
  # If you have not set up the table the plugin will create it for you!
  table: economy
  # If the plugin loses connection it will auto-reconnect to the database
  auto-reconnect: true
  # Using an SSL certificate?
  useSSL: false


# This is the section where you can customize the /bank command
bank:
  # You want to use the bank feature?
  use: true
  # Interests feature
  interest:
    use: true
    # How frequently the bank will add the interests?
    time: 300 # <- In seconds!
    # Interest rate (%)
    percentage: 10
    # The player needs to be online to receive the interest?
    require-online: true